<?php

declare(strict_types=1);

namespace Sixty;

/**
 * DDSketch — quantile sketch with *relative* error guarantees.
 *
 * A byte-for-byte port of packages/core/src/sketch.js. The format is the
 * contract between every agent and the collector: the collector decodes these
 * blobs with the JavaScript implementation, merges them across releases, and
 * computes the percentiles a finding is made of. A PHP sketch that decoded into
 * slightly different buckets would not error anywhere — it would produce a p95
 * that quietly disagrees with the one a Node or Rails service in the same
 * organization reports, which is the kind of wrong this project exists to
 * avoid.
 *
 * So the header layout, the varint encoding and the bucket indexing are
 * reproduced exactly rather than reimplemented idiomatically, and
 * tests/SketchTest.php checks the bytes against fixtures generated by the
 * JavaScript writer.
 *
 * Why a sketch at all: latency is heavy-tailed and multimodal. A mean moves too
 * little to detect a real p95 regression, and merges of DDSketches are lossless
 * — which is what lets the collector store one sketch per 5-minute bucket and
 * union arbitrary windows without the numbers drifting.
 */
final class Sketch
{
    private const MAGIC = 0xd5;
    private const VERSION = 1;
    private const MIN_VALUE = 1e-9;
    /** 1 magic + 1 version + 5 doubles + 1 flag. */
    public const HEADER_BYTES = 43;

    private float $gamma;
    private float $logGamma;

    /**
     * Two derived constants per alpha, computed once for the process.
     *
     * Every sketch construction called `log()`, and the flush constructs one
     * per sketch per window — so a merge of two hundred windows was calling it
     * a couple of thousand times to get the same two numbers back.
     *
     * @var array<string, array{0: float, 1: float}>
     */
    private static array $constants = [];

    /** @var array<int, int|float> bucket index => count */
    private array $buckets = [];
    private float $zeroCount = 0.0;
    private float $count = 0.0;
    private float $sum = 0.0;
    private float $min = INF;
    private float $max = -INF;

    public function __construct(private float $alpha = 0.01)
    {
        $key = (string) $alpha;
        if (!isset(self::$constants[$key])) {
            $gamma = (1 + $alpha) / (1 - $alpha);
            self::$constants[$key] = [$gamma, log($gamma)];
        }
        [$this->gamma, $this->logGamma] = self::$constants[$key];
    }

    public function add(float $value, int $count = 1): self
    {
        if (is_nan($value) || is_infinite($value) || $count <= 0) {
            return $this;
        }
        if ($value < 0) {
            $value = 0.0;
        }

        $this->count += $count;
        $this->sum += $value * $count;
        if ($value < $this->min) {
            $this->min = $value;
        }
        if ($value > $this->max) {
            $this->max = $value;
        }

        if ($value < self::MIN_VALUE) {
            $this->zeroCount += $count;

            return $this;
        }

        $i = $this->index($value);
        $this->buckets[$i] = ($this->buckets[$i] ?? 0) + $count;

        return $this;
    }

    /** Lossless when both sketches share alpha. Mutates $this. */
    public function merge(?self $other): self
    {
        if ($other === null || $other->count === 0.0) {
            return $this;
        }
        if (abs($other->alpha - $this->alpha) > 1e-12) {
            throw new \InvalidArgumentException('cannot merge sketches with different alpha');
        }

        foreach ($other->buckets as $i => $c) {
            $this->buckets[$i] = ($this->buckets[$i] ?? 0) + $c;
        }
        $this->zeroCount += $other->zeroCount;
        $this->count += $other->count;
        $this->sum += $other->sum;
        if ($other->min < $this->min) {
            $this->min = $other->min;
        }
        if ($other->max > $this->max) {
            $this->max = $other->max;
        }

        return $this;
    }

    public function count(): float
    {
        return $this->count;
    }

    public function sum(): float
    {
        return $this->sum;
    }

    public function quantile(float $q): ?float
    {
        if ($this->count === 0.0) {
            return null;
        }
        if ($q <= 0) {
            return $this->min;
        }
        if ($q >= 1) {
            return $this->max;
        }

        $rank = $q * ($this->count - 1);
        if ($rank < $this->zeroCount) {
            return 0.0;
        }

        $acc = $this->zeroCount;
        $indices = array_keys($this->buckets);
        sort($indices);
        foreach ($indices as $i) {
            $acc += $this->buckets[$i];
            if ($acc > $rank) {
                // Clamped to observed bounds: a bucket's nominal value can fall
                // slightly outside [min, max], and a p99 above any observed
                // value reads as a bug to anyone eyeballing the numbers.
                return min(max($this->valueAt($i), $this->min), $this->max);
            }
        }

        return $this->max;
    }

    /**
     * Compact binary form: header + zigzag-varint delta-encoded buckets.
     *
     * ── Why this is written as one long function ─────────────────────────
     *
     * It is the hottest code in the agent. Every operation carries two to four
     * sketches and every one of them is encoded on the way out, so at four
     * operations a request this runs ten times per request — and it measured at
     * 2.6µs a call when the varint writer was a method and the header was six
     * `pack()` calls concatenated. PHP charges for both: a function call is
     * ~0.05µs, and there are two per bucket.
     *
     * Inlined and packed in one go it is under a microsecond, and the bytes are
     * identical — which is not a matter of opinion, because tests/WireTest.php
     * compares them to fixtures written by the JavaScript implementation the
     * collector decodes with.
     */
    public function toBinary(): string
    {
        $indices = array_keys($this->buckets);
        sort($indices);

        $body = '';
        $prev = 0;
        foreach ($indices as $i) {
            // zigzag, so a negative delta costs the same as a positive one
            $delta = $i - $prev;
            $n = $delta >= 0 ? $delta * 2 : -$delta * 2 - 1;
            while ($n >= 0x80) {
                $body .= chr(($n & 0x7f) | 0x80);
                $n >>= 7;
            }
            $body .= chr($n);

            // The count. Bucket counts are integers by construction — `add()`
            // takes an int and merges add ints — so there is nothing to round.
            $n = $this->buckets[$i];
            while ($n >= 0x80) {
                $body .= chr(($n & 0x7f) | 0x80);
                $n >>= 7;
            }
            $body .= chr($n);

            $prev = $i;
        }

        // 'e' is an IEEE-754 double, little-endian — the same layout DataView
        // writes with littleEndian = true.
        return pack(
            'C2e5C',
            self::MAGIC,
            self::VERSION,
            $this->alpha,
            $this->zeroCount,
            $this->sum,
            $this->count === 0.0 ? 0.0 : $this->min,
            $this->count === 0.0 ? 0.0 : $this->max,
            $indices === [] ? 0 : 1,
        ) . $body;
    }

    /** Base64 of the binary form, which is how the agent ships it over JSON. */
    public function toBase64(): string
    {
        return base64_encode($this->toBinary());
    }

    /**
     * Only tests and the cross-request buffer decode; the request path is
     * write-only. It lives here anyway because a codec whose two halves are in
     * different languages is a codec nobody can check locally.
     */
    public static function fromBinary(string $bytes): self
    {
        if (strlen($bytes) < self::HEADER_BYTES) {
            return new self();
        }
        if (ord($bytes[0]) !== self::MAGIC) {
            throw new \InvalidArgumentException('not a DDSketch buffer');
        }
        $version = ord($bytes[1]);
        if ($version !== self::VERSION) {
            throw new \InvalidArgumentException("unsupported sketch version {$version}");
        }

        /** @var array{1: float, 2: float, 3: float, 4: float, 5: float} $head */
        $head = unpack('e5', substr($bytes, 2, 40));
        $sketch = new self($head[1]);
        $sketch->zeroCount = $head[2];
        $sketch->sum = $head[3];
        $min = $head[4];
        $max = $head[5];

        // Inlined for the same reason the writer is: this runs once per sketch
        // per window on the flush path, and a method call per varint was a
        // third of the cost of reading one.
        $offset = self::HEADER_BYTES;
        $total = $sketch->zeroCount;
        $prev = 0;
        $length = strlen($bytes);
        while ($offset < $length) {
            $delta = 0;
            $shift = 0;
            do {
                $byte = ord($bytes[$offset++]);
                $delta |= ($byte & 0x7f) << $shift;
                $shift += 7;
            } while ($byte >= 0x80 && $offset < $length);

            $count = 0;
            $shift = 0;
            do {
                $byte = ord($bytes[$offset++]);
                $count |= ($byte & 0x7f) << $shift;
                $shift += 7;
            } while ($byte >= 0x80 && $offset < $length);

            $i = $prev + (($delta & 1) === 0 ? $delta >> 1 : -(($delta + 1) >> 1));
            $sketch->buckets[$i] = ($sketch->buckets[$i] ?? 0) + $count;
            $total += $count;
            $prev = $i;
        }

        $sketch->count = $total;
        $sketch->min = $total > 0 ? $min : INF;
        $sketch->max = $total > 0 ? $max : -INF;

        return $sketch;
    }

    /**
     * Merge encoded sketches into one encoded sketch, without ever building a
     * Sketch object.
     *
     * This is the flush path's inner loop: a merge of two hundred windows
     * decodes four to six blobs per operation per window, and each decode was
     * allocating an object, running its constructor and calling a method to
     * fold in the next one. Reading straight into local arrays and writing the
     * result out once skips all of that — the header arithmetic is nine lines,
     * and it is the same nine lines the constructor would have run.
     *
     * @param array<int, string> $blobs base64, at least one
     */
    public static function mergeEncoded(array $blobs): ?string
    {
        $buckets = [];
        $alpha = null;
        $zeroCount = 0.0;
        $count = 0.0;
        $sum = 0.0;
        $min = INF;
        $max = -INF;

        foreach ($blobs as $blob) {
            $bytes = base64_decode($blob, true);
            if ($bytes === false || strlen($bytes) < self::HEADER_BYTES || ord($bytes[0]) !== self::MAGIC) {
                continue;
            }

            /** @var array{1: float, 2: float, 3: float, 4: float, 5: float} $head */
            $head = unpack('e5', substr($bytes, 2, 40));
            $alpha ??= $head[1];
            $zeroCount += $head[2];
            $sum += $head[3];

            $offset = self::HEADER_BYTES;
            $length = strlen($bytes);
            $prev = 0;
            $total = $head[2];
            while ($offset < $length) {
                $delta = 0;
                $shift = 0;
                do {
                    $byte = ord($bytes[$offset++]);
                    $delta |= ($byte & 0x7f) << $shift;
                    $shift += 7;
                } while ($byte >= 0x80 && $offset < $length);

                $c = 0;
                $shift = 0;
                do {
                    $byte = ord($bytes[$offset++]);
                    $c |= ($byte & 0x7f) << $shift;
                    $shift += 7;
                } while ($byte >= 0x80 && $offset < $length);

                $i = $prev + (($delta & 1) === 0 ? $delta >> 1 : -(($delta + 1) >> 1));
                $buckets[$i] = ($buckets[$i] ?? 0) + $c;
                $total += $c;
                $prev = $i;
            }

            // min and max are only meaningful when the sketch saw something,
            // and an empty one writes zeros for both — folding those in would
            // report a minimum of zero for every operation.
            if ($total > 0) {
                $count += $total;
                if ($head[4] < $min) {
                    $min = $head[4];
                }
                if ($head[5] > $max) {
                    $max = $head[5];
                }
            }
        }

        if ($alpha === null) {
            return null;
        }

        ksort($buckets);
        $body = '';
        $prev = 0;
        foreach ($buckets as $i => $c) {
            $n = ($i - $prev) >= 0 ? ($i - $prev) * 2 : -($i - $prev) * 2 - 1;
            while ($n >= 0x80) {
                $body .= chr(($n & 0x7f) | 0x80);
                $n >>= 7;
            }
            $body .= chr($n);
            $n = $c;
            while ($n >= 0x80) {
                $body .= chr(($n & 0x7f) | 0x80);
                $n >>= 7;
            }
            $body .= chr($n);
            $prev = $i;
        }

        return base64_encode(pack(
            'C2e5C',
            self::MAGIC,
            self::VERSION,
            $alpha,
            $zeroCount,
            $sum,
            $count === 0.0 ? 0.0 : $min,
            $count === 0.0 ? 0.0 : $max,
            $buckets === [] ? 0 : 1,
        ) . $body);
    }

    /** Merge many serialized sketches into one. Used by the cross-request buffer. */
    public static function mergeBase64(array $encoded): ?self
    {
        $out = null;
        foreach ($encoded as $blob) {
            if (!is_string($blob) || $blob === '') {
                continue;
            }
            $decoded = base64_decode($blob, true);
            if ($decoded === false) {
                continue;
            }
            $sketch = self::fromBinary($decoded);
            $out = $out === null ? $sketch : $out->merge($sketch);
        }

        return $out;
    }

    private function index(float $value): int
    {
        return (int) ceil(log($value) / $this->logGamma);
    }

    private function valueAt(int $index): float
    {
        return (2 * ($this->gamma ** $index)) / ($this->gamma + 1);
    }

}
